#!/bin/bash

# Demo script showing MindCore · Forge in action
# This creates a sample project to demonstrate the tool

# Get the directory of this script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export FORGE_DIR="$SCRIPT_DIR"

echo "🔨 MindCore · Forge Demo"
echo "========================"
echo ""
echo "This demo will show you what MindCore · Forge generates."
echo "We'll create a sample React + Express project."
echo ""

# Clean up any previous demo
DEMO_DIR="/tmp/forge-demo"
rm -rf "$DEMO_DIR"
mkdir -p "$DEMO_DIR"

echo "Demo project will be created at: $DEMO_DIR"
echo ""

# Create a demo test that bypasses interactive prompts
cd "$DEMO_DIR"

cat > generate-demo.js << 'EOF'
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Dynamically resolve the forge directory
const forgeDir = process.env.FORGE_DIR || path.join(__dirname, '..', '..');

// Load templates using resolved path
const frontendTemplates = require(path.join(forgeDir, 'src/templates/frontend.js'));
const backendTemplates = require(path.join(forgeDir, 'src/templates/backend.js'));

const config = {
  projectName: 'demo-hackathon-project',
  stack: 'react-express',
  projectDescription: 'A demo hackathon project generated by MindCore · Forge',
  name: 'React + Express',
  frontend: 'react',
  backend: 'express'
};

console.log('Generating demo project...\n');

// Create project structure
const projectPath = path.join(process.cwd(), config.projectName);
fs.mkdirSync(projectPath);
fs.mkdirSync(path.join(projectPath, 'frontend'));
fs.mkdirSync(path.join(projectPath, 'backend'));
fs.mkdirSync(path.join(projectPath, 'frontend/src'));
fs.mkdirSync(path.join(projectPath, 'frontend/public'));
fs.mkdirSync(path.join(projectPath, 'backend/src'));

console.log('✓ Created project structure');

// Generate frontend
const frontendTemplate = frontendTemplates.react(config);
fs.writeFileSync(
  path.join(projectPath, 'frontend/package.json'),
  JSON.stringify(frontendTemplate.packageJson, null, 2)
);

Object.keys(frontendTemplate.files).forEach(fileName => {
  const filePath = path.join(projectPath, 'frontend', fileName);
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(filePath, frontendTemplate.files[fileName]);
});

console.log('✓ Generated frontend (React)');

// Generate backend
const backendTemplate = backendTemplates.express(config);
fs.writeFileSync(
  path.join(projectPath, 'backend/package.json'),
  JSON.stringify(backendTemplate.packageJson, null, 2)
);

Object.keys(backendTemplate.files).forEach(fileName => {
  const filePath = path.join(projectPath, 'backend', fileName);
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(filePath, backendTemplate.files[fileName]);
});

console.log('✓ Generated backend (Express)');

// Generate README
const readme = `# ${config.projectName}

${config.projectDescription}

## Stack

- **Frontend**: REACT
- **Backend**: EXPRESS

## Quick Start

\`\`\`bash
# Frontend
cd frontend
npm install
npm start

# Backend (in another terminal)
cd backend
npm install
npm start
\`\`\`

Frontend: http://localhost:3000
Backend: http://localhost:5000

---
Generated by MindCore · Forge 🚀
`;

fs.writeFileSync(path.join(projectPath, 'README.md'), readme);

// Generate .gitignore
const gitignore = `node_modules/
*.log
.DS_Store
dist/
build/
`;
fs.writeFileSync(path.join(projectPath, '.gitignore'), gitignore);

console.log('✓ Generated project files');
console.log('\n✨ Demo project generated successfully!');
console.log(`\nLocation: ${projectPath}`);
EOF

node generate-demo.js

echo ""
echo "Demo project structure:"
echo "======================="
tree -L 3 -I 'node_modules' "$DEMO_DIR/demo-hackathon-project" 2>/dev/null || find "$DEMO_DIR/demo-hackathon-project" -type f -o -type d | grep -v node_modules | head -20

echo ""
echo "Sample files generated:"
echo "======================="
echo ""
echo "Frontend package.json:"
cat "$DEMO_DIR/demo-hackathon-project/frontend/package.json" | head -15
echo "..."
echo ""
echo "Backend src/index.js (first 20 lines):"
head -20 "$DEMO_DIR/demo-hackathon-project/backend/src/index.js"
echo "..."
echo ""
echo "✅ Demo complete!"
echo ""
echo "To run the demo project:"
echo "  cd $DEMO_DIR/demo-hackathon-project"
echo "  cd frontend && npm install && npm start"
echo "  # In another terminal:"
echo "  cd backend && npm install && npm start"
