// CLI and Desktop application templates

function goCLI(config) {
  return {
    files: {
      'go.mod': `module ${config.projectName}

go 1.21

require github.com/spf13/cobra v1.8.0

require (
\tgithub.com/inconshreveable/mousetrap v1.1.0 // indirect
\tgithub.com/spf13/pflag v1.0.5 // indirect
)`,
      'main.go': `package main

import (
\t"fmt"
\t"os"

\t"github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
\tUse:   "${config.projectName}",
\tShort: "${config.projectDescription}",
\tLong:  \`${config.projectDescription}

This CLI tool was generated by MindCore · Forge for hackathons.\`,
\tRun: func(cmd *cobra.Command, args []string) {
\t\tfmt.Println("🔨 ${config.projectName}")
\t\tfmt.Println("${config.projectDescription}")
\t\tfmt.Println("")
\t\tfmt.Println("Use --help to see available commands")
\t},
}

var greetCmd = &cobra.Command{
\tUse:   "greet [name]",
\tShort: "Greet someone",
\tArgs:  cobra.ExactArgs(1),
\tRun: func(cmd *cobra.Command, args []string) {
\t\tname := args[0]
\t\tfmt.Printf("Hello, %s! Welcome to ${config.projectName}\\n", name)
\t},
}

var versionCmd = &cobra.Command{
\tUse:   "version",
\tShort: "Print the version number",
\tRun: func(cmd *cobra.Command, args []string) {
\t\tfmt.Println("${config.projectName} v1.0.0")
\t},
}

func init() {
\trootCmd.AddCommand(greetCmd)
\trootCmd.AddCommand(versionCmd)
}

func main() {
\tif err := rootCmd.Execute(); err != nil {
\t\tfmt.Fprintln(os.Stderr, err)
\t\tos.Exit(1)
\t}
}`,
      'README.md': `# ${config.projectName}

${config.projectDescription}

## Installation

\`\`\`bash
go build -o ${config.projectName}
\`\`\`

## Usage

\`\`\`bash
# Run the CLI
./${config.projectName}

# Greet someone
./${config.projectName} greet World

# Check version
./${config.projectName} version

# See all commands
./${config.projectName} --help
\`\`\`

## Development

\`\`\`bash
go run main.go
\`\`\`
`,
      '.gitignore': `# Binaries
${config.projectName}
*.exe
*.exe~
*.dll
*.so
*.dylib

# Test binary
*.test

# Output of the go coverage tool
*.out

# Go workspace file
go.work`
    }
  };
}

function pythonCLI(config) {
  return {
    requirements: `click>=8.1.7
colorama>=0.4.6`,
    files: {
      'cli.py': `#!/usr/bin/env python3
"""
${config.projectName}
${config.projectDescription}
"""

import click
from colorama import init, Fore, Style

init(autoreset=True)

@click.group()
@click.version_option(version='1.0.0')
def cli():
    """${config.projectDescription}"""
    pass

@cli.command()
def hello():
    """Say hello"""
    click.echo(f"{Fore.CYAN}🔨 ${config.projectName}{Style.RESET_ALL}")
    click.echo(f"{config.projectDescription}")
    click.echo()
    click.echo("Use --help to see available commands")

@cli.command()
@click.argument('name')
def greet(name):
    """Greet someone by name"""
    click.echo(f"{Fore.GREEN}Hello, {name}! Welcome to ${config.projectName}{Style.RESET_ALL}")

@cli.command()
@click.option('--count', default=1, help='Number of times to repeat')
@click.argument('message')
def repeat(count, message):
    """Repeat a message N times"""
    for i in range(count):
        click.echo(f"{i+1}. {message}")

if __name__ == '__main__':
    cli()`,
      'README.md': `# ${config.projectName}

${config.projectDescription}

## Installation

\`\`\`bash
pip install -r requirements.txt
\`\`\`

## Usage

\`\`\`bash
# Run the CLI
python cli.py hello

# Greet someone
python cli.py greet World

# Repeat a message
python cli.py repeat "Hello Hackathon" --count 3

# See all commands
python cli.py --help
\`\`\`

## Make it executable

\`\`\`bash
chmod +x cli.py
./cli.py hello
\`\`\`
`,
      '.gitignore': `__pycache__/
*.py[cod]
*$py.class
*.so
.Python
venv/
env/
.venv/
pip-log.txt`
    }
  };
}

function rustCLI(config) {
  return {
    files: {
      'Cargo.toml': `[package]
name = "${config.projectName}"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
colored = "2.1"`,
      'src/main.rs': `use clap::{Parser, Subcommand};
use colored::*;

/// ${config.projectDescription}
#[derive(Parser)]
#[command(author, version, about, long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Option<Commands>,
}

#[derive(Subcommand)]
enum Commands {
    /// Say hello
    Hello,
    /// Greet someone by name
    Greet { name: String },
    /// Repeat a message N times
    Repeat {
        message: String,
        #[arg(short, long, default_value_t = 1)]
        count: usize,
    },
}

fn main() {
    let cli = Cli::parse();

    match &cli.command {
        Some(Commands::Hello) => {
            println!("{}", "🔨 ${config.projectName}".cyan().bold());
            println!("{}", "${config.projectDescription}");
            println!();
            println!("Use --help to see available commands");
        }
        Some(Commands::Greet { name }) => {
            println!("{}", format!("Hello, {}! Welcome to ${config.projectName}", name).green());
        }
        Some(Commands::Repeat { message, count }) => {
            for i in 1..=*count {
                println!("{}. {}", i, message);
            }
        }
        None => {
            println!("{}", "🔨 ${config.projectName}".cyan().bold());
            println!("{}", "${config.projectDescription}");
            println!();
            println!("Use --help to see available commands");
        }
    }
}`,
      'README.md': `# ${config.projectName}

${config.projectDescription}

## Installation

\`\`\`bash
cargo build --release
\`\`\`

The binary will be in \`target/release/${config.projectName}\`

## Usage

\`\`\`bash
# Run the CLI
cargo run -- hello

# Or use the compiled binary
./target/release/${config.projectName} hello

# Greet someone
cargo run -- greet World

# Repeat a message
cargo run -- repeat "Hello Hackathon" --count 3

# See all commands
cargo run -- --help
\`\`\`

## Development

\`\`\`bash
cargo run
\`\`\`
`,
      '.gitignore': `/target
Cargo.lock`
    }
  };
}

function electron(config) {
  return {
    packageJson: {
      name: config.projectName,
      version: "1.0.0",
      description: config.projectDescription,
      main: "main.js",
      scripts: {
        start: "electron .",
        build: "electron-builder"
      },
      dependencies: {
        electron: "^27.0.0"
      },
      devDependencies: {
        "electron-builder": "^24.6.4"
      }
    },
    files: {
      'main.js': `const { app, BrowserWindow } = require('electron');
const path = require('path');

function createWindow() {
  const win = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: false,
      contextIsolation: true
    }
  });

  win.loadFile('index.html');
  
  // Open DevTools in development
  if (process.env.NODE_ENV === 'development') {
    win.webContents.openDevTools();
  }
}

app.whenReady().then(() => {
  createWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});`,
      'preload.js': `const { contextBridge } = require('electron');

contextBridge.exposeInMainWorld('api', {
  platform: process.platform,
  version: process.versions.electron
});`,
      'index.html': `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; style-src 'self' 'unsafe-inline'">
    <title>${config.projectName}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Helvetica', 'Arial', sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            color: white;
        }
        .container {
            text-align: center;
            padding: 40px;
        }
        h1 {
            font-size: 48px;
            margin-bottom: 20px;
        }
        p {
            font-size: 20px;
            margin-bottom: 40px;
        }
        .card {
            background: rgba(255, 255, 255, 0.1);
            backdrop-filter: blur(10px);
            border-radius: 20px;
            padding: 40px;
            margin: 20px 0;
        }
        button {
            background: white;
            color: #667eea;
            border: none;
            padding: 15px 30px;
            border-radius: 10px;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            margin: 0 10px;
            transition: transform 0.2s;
        }
        button:hover {
            transform: translateY(-2px);
        }
        #counter {
            font-size: 72px;
            font-weight: bold;
            margin: 20px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🔨 ${config.projectName}</h1>
        <p>${config.projectDescription}</p>
        
        <div class="card">
            <h2>Counter Example</h2>
            <div id="counter">0</div>
            <button onclick="increment()">Increment</button>
            <button onclick="decrement()">Decrement</button>
            <button onclick="reset()">Reset</button>
        </div>

        <div class="card">
            <h2>App Info</h2>
            <p>Platform: <span id="platform"></span></p>
            <p>Electron: <span id="version"></span></p>
        </div>
    </div>

    <script>
        let counter = 0;
        const counterEl = document.getElementById('counter');

        function increment() {
            counter++;
            counterEl.textContent = counter;
        }

        function decrement() {
            counter--;
            counterEl.textContent = counter;
        }

        function reset() {
            counter = 0;
            counterEl.textContent = counter;
        }

        // Display platform info
        document.getElementById('platform').textContent = window.api.platform;
        document.getElementById('version').textContent = window.api.version;
    </script>
</body>
</html>`,
      'README.md': `# ${config.projectName}

${config.projectDescription}

## Running the App

\`\`\`bash
npm install
npm start
\`\`\`

## Building for Distribution

\`\`\`bash
npm run build
\`\`\`

This will create installers for your platform in the \`dist\` directory.

## Development

The app uses Electron with a simple HTML/CSS/JS frontend. Edit \`index.html\` for the UI and \`main.js\` for the Electron backend.
`,
      '.gitignore': `node_modules/
dist/
*.log`
    }
  };
}

module.exports = {
  goCLI,
  pythonCLI,
  rustCLI,
  electron
};
