function react(config) {
  return {
    packageJson: {
      name: `${config.projectName}-frontend`,
      version: "1.0.0",
      private: true,
      scripts: {
        start: "react-scripts start",
        build: "react-scripts build",
        test: "react-scripts test",
        eject: "react-scripts eject"
      },
      dependencies: {
        react: "^18.2.0",
        "react-dom": "^18.2.0",
        "react-scripts": "5.0.1"
      },
      eslintConfig: {
        extends: ["react-app"]
      },
      browserslist: {
        production: [">0.2%", "not dead", "not op_mini all"],
        development: ["last 1 chrome version", "last 1 firefox version", "last 1 safari version"]
      }
    },
    files: {
      'public/index.html': `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="${config.projectDescription}" />
    <title>${config.projectName}</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>`,
      'src/index.js': `import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`,
      'src/App.js': `import React, { useState, useEffect } from 'react';
import './App.css';

function App() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      setLoading(true);
      const response = await fetch('http://localhost:${config.backend === 'fastapi' ? '8000' : '5000'}/api/data');
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
      const result = await response.json();
      setData(result);
      setError(null);
    } catch (err) {
      setError(err.message);
      console.error('Error fetching data:', err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="App">
      <header className="App-header">
        <h1>🔨 ${config.projectName}</h1>
        <p>{config.projectDescription}</p>
      </header>
      
      <main className="App-main">
        <section className="status-section">
          <h2>API Status</h2>
          {loading && <p className="loading">Loading...</p>}
          {error && (
            <div className="error">
              <p>❌ Error connecting to API: {error}</p>
              <p className="hint">Make sure the backend is running on port ${config.backend === 'fastapi' ? '8000' : '5000'}</p>
            </div>
          )}
          {data && !loading && !error && (
            <div className="success">
              <p>✅ Connected to API</p>
              <pre>{JSON.stringify(data, null, 2)}</pre>
            </div>
          )}
          <button onClick={fetchData} disabled={loading}>
            Refresh Data
          </button>
        </section>

        <section className="info-section">
          <h2>Stack Info</h2>
          <ul>
            <li><strong>Frontend:</strong> React</li>
            <li><strong>Backend:</strong> ${config.backend.toUpperCase()}</li>
            <li><strong>Generated by:</strong> MindCore · Forge</li>
          </ul>
        </section>
      </main>

      <footer className="App-footer">
        <p>Built for hackathons. Ready to code. 🚀</p>
      </footer>
    </div>
  );
}

export default App;`,
      'src/App.css': `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

.App {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
}

.App-header {
  padding: 2rem;
  text-align: center;
  background: rgba(0, 0, 0, 0.2);
  backdrop-filter: blur(10px);
}

.App-header h1 {
  font-size: 2.5rem;
  margin-bottom: 0.5rem;
}

.App-main {
  flex: 1;
  padding: 2rem;
  max-width: 1200px;
  width: 100%;
  margin: 0 auto;
}

.status-section,
.info-section {
  background: rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(10px);
  border-radius: 12px;
  padding: 2rem;
  margin-bottom: 2rem;
}

.status-section h2,
.info-section h2 {
  margin-bottom: 1rem;
  font-size: 1.5rem;
}

.loading {
  color: #ffd700;
  font-style: italic;
}

.error {
  background: rgba(255, 0, 0, 0.2);
  padding: 1rem;
  border-radius: 8px;
  border-left: 4px solid #ff4444;
}

.error .hint {
  margin-top: 0.5rem;
  font-size: 0.9rem;
  color: #ffcccc;
}

.success {
  background: rgba(0, 255, 0, 0.2);
  padding: 1rem;
  border-radius: 8px;
  border-left: 4px solid #44ff44;
}

.success pre {
  background: rgba(0, 0, 0, 0.3);
  padding: 1rem;
  border-radius: 4px;
  overflow-x: auto;
  margin-top: 0.5rem;
  text-align: left;
}

button {
  background: white;
  color: #667eea;
  border: none;
  padding: 0.75rem 1.5rem;
  border-radius: 8px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  margin-top: 1rem;
  transition: all 0.3s ease;
}

button:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
}

button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.info-section ul {
  list-style: none;
}

.info-section li {
  padding: 0.5rem 0;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.info-section li:last-child {
  border-bottom: none;
}

.App-footer {
  padding: 2rem;
  text-align: center;
  background: rgba(0, 0, 0, 0.2);
  backdrop-filter: blur(10px);
}`,
      'src/index.css': `body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

code {
  font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New',
    monospace;
}`
    }
  };
}

function vue(config) {
  return {
    packageJson: {
      name: `${config.projectName}-frontend`,
      version: "1.0.0",
      private: true,
      scripts: {
        start: "vue-cli-service serve",
        build: "vue-cli-service build",
        lint: "vue-cli-service lint"
      },
      dependencies: {
        vue: "^3.3.4",
        axios: "^1.5.0"
      },
      devDependencies: {
        "@vue/cli-service": "^5.0.8",
        "@vue/compiler-sfc": "^3.3.4"
      }
    },
    files: {
      'public/index.html': `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>${config.projectName}</title>
  </head>
  <body>
    <noscript>
      <strong>We're sorry but this app doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
  </body>
</html>`,
      'src/main.js': `import { createApp } from 'vue';
import App from './App.vue';

createApp(App).mount('#app');`,
      'src/App.vue': `<template>
  <div id="app">
    <header class="app-header">
      <h1>🔨 ${config.projectName}</h1>
      <p>{{ description }}</p>
    </header>

    <main class="app-main">
      <section class="status-section">
        <h2>API Status</h2>
        <p v-if="loading" class="loading">Loading...</p>
        <div v-if="error" class="error">
          <p>❌ Error connecting to API: {{ error }}</p>
          <p class="hint">Make sure the backend is running on port ${config.backend === 'fastapi' ? '8000' : '5000'}</p>
        </div>
        <div v-if="data && !loading && !error" class="success">
          <p>✅ Connected to API</p>
          <pre>{{ JSON.stringify(data, null, 2) }}</pre>
        </div>
        <button @click="fetchData" :disabled="loading">Refresh Data</button>
      </section>

      <section class="info-section">
        <h2>Stack Info</h2>
        <ul>
          <li><strong>Frontend:</strong> Vue.js</li>
          <li><strong>Backend:</strong> ${config.backend.toUpperCase()}</li>
          <li><strong>Generated by:</strong> MindCore · Forge</li>
        </ul>
      </section>
    </main>

    <footer class="app-footer">
      <p>Built for hackathons. Ready to code. 🚀</p>
    </footer>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: 'App',
  data() {
    return {
      description: '${config.projectDescription}',
      data: null,
      loading: true,
      error: null
    };
  },
  mounted() {
    this.fetchData();
  },
  methods: {
    async fetchData() {
      try {
        this.loading = true;
        this.error = null;
        const response = await axios.get('http://localhost:${config.backend === 'fastapi' ? '8000' : '5000'}/api/data');
        this.data = response.data;
      } catch (err) {
        this.error = err.message;
        console.error('Error fetching data:', err);
      } finally {
        this.loading = false;
      }
    }
  }
};
</script>

<style>
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

#app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
}

.app-header {
  padding: 2rem;
  text-align: center;
  background: rgba(0, 0, 0, 0.2);
  backdrop-filter: blur(10px);
}

.app-header h1 {
  font-size: 2.5rem;
  margin-bottom: 0.5rem;
}

.app-main {
  flex: 1;
  padding: 2rem;
  max-width: 1200px;
  width: 100%;
  margin: 0 auto;
}

.status-section,
.info-section {
  background: rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(10px);
  border-radius: 12px;
  padding: 2rem;
  margin-bottom: 2rem;
}

h2 {
  margin-bottom: 1rem;
  font-size: 1.5rem;
}

.loading {
  color: #ffd700;
  font-style: italic;
}

.error {
  background: rgba(255, 0, 0, 0.2);
  padding: 1rem;
  border-radius: 8px;
  border-left: 4px solid #ff4444;
}

.error .hint {
  margin-top: 0.5rem;
  font-size: 0.9rem;
  color: #ffcccc;
}

.success {
  background: rgba(0, 255, 0, 0.2);
  padding: 1rem;
  border-radius: 8px;
  border-left: 4px solid #44ff44;
}

.success pre {
  background: rgba(0, 0, 0, 0.3);
  padding: 1rem;
  border-radius: 4px;
  overflow-x: auto;
  margin-top: 0.5rem;
  text-align: left;
}

button {
  background: white;
  color: #667eea;
  border: none;
  padding: 0.75rem 1.5rem;
  border-radius: 8px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  margin-top: 1rem;
  transition: all 0.3s ease;
}

button:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
}

button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.info-section ul {
  list-style: none;
}

.info-section li {
  padding: 0.5rem 0;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.info-section li:last-child {
  border-bottom: none;
}

.app-footer {
  padding: 2rem;
  text-align: center;
  background: rgba(0, 0, 0, 0.2);
  backdrop-filter: blur(10px);
}
</style>`,
      'vue.config.js': `module.exports = {
  lintOnSave: false,
  devServer: {
    port: 3000
  }
};`
    }
  };
}

function vanilla(config) {
  return {
    packageJson: {
      name: `${config.projectName}-frontend`,
      version: "1.0.0",
      private: true,
      scripts: {
        start: "npx http-server -p 3000 -o"
      },
      devDependencies: {
        "http-server": "^14.1.1"
      }
    },
    files: {
      'public/index.html': `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${config.projectName}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div id="app">
        <header class="app-header">
            <h1>🔨 ${config.projectName}</h1>
            <p>${config.projectDescription}</p>
        </header>

        <main class="app-main">
            <section class="status-section">
                <h2>API Status</h2>
                <div id="status-container">
                    <p class="loading">Loading...</p>
                </div>
                <button id="refresh-btn">Refresh Data</button>
            </section>

            <section class="info-section">
                <h2>Stack Info</h2>
                <ul>
                    <li><strong>Frontend:</strong> Vanilla JavaScript</li>
                    <li><strong>Backend:</strong> ${config.backend.toUpperCase()}</li>
                    <li><strong>Generated by:</strong> MindCore · Forge</li>
                </ul>
            </section>
        </main>

        <footer class="app-footer">
            <p>Built for hackathons. Ready to code. 🚀</p>
        </footer>
    </div>

    <script src="app.js"></script>
</body>
</html>`,
      'public/style.css': `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
}

#app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
}

.app-header {
  padding: 2rem;
  text-align: center;
  background: rgba(0, 0, 0, 0.2);
  backdrop-filter: blur(10px);
}

.app-header h1 {
  font-size: 2.5rem;
  margin-bottom: 0.5rem;
}

.app-main {
  flex: 1;
  padding: 2rem;
  max-width: 1200px;
  width: 100%;
  margin: 0 auto;
}

.status-section,
.info-section {
  background: rgba(255, 255, 255, 0.1);
  backdrop-filter: blur(10px);
  border-radius: 12px;
  padding: 2rem;
  margin-bottom: 2rem;
}

h2 {
  margin-bottom: 1rem;
  font-size: 1.5rem;
}

.loading {
  color: #ffd700;
  font-style: italic;
}

.error {
  background: rgba(255, 0, 0, 0.2);
  padding: 1rem;
  border-radius: 8px;
  border-left: 4px solid #ff4444;
}

.error .hint {
  margin-top: 0.5rem;
  font-size: 0.9rem;
  color: #ffcccc;
}

.success {
  background: rgba(0, 255, 0, 0.2);
  padding: 1rem;
  border-radius: 8px;
  border-left: 4px solid #44ff44;
}

.success pre {
  background: rgba(0, 0, 0, 0.3);
  padding: 1rem;
  border-radius: 4px;
  overflow-x: auto;
  margin-top: 0.5rem;
  text-align: left;
}

button {
  background: white;
  color: #667eea;
  border: none;
  padding: 0.75rem 1.5rem;
  border-radius: 8px;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
  margin-top: 1rem;
  transition: all 0.3s ease;
}

button:hover:not(:disabled) {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
}

button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.info-section ul {
  list-style: none;
}

.info-section li {
  padding: 0.5rem 0;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.info-section li:last-child {
  border-bottom: none;
}

.app-footer {
  padding: 2rem;
  text-align: center;
  background: rgba(0, 0, 0, 0.2);
  backdrop-filter: blur(10px);
}`,
      'public/app.js': `const API_BASE_URL = 'http://localhost:${config.backend === 'fastapi' ? '8000' : '5000'}';

let isLoading = false;

async function fetchData() {
    if (isLoading) return;

    const statusContainer = document.getElementById('status-container');
    const refreshBtn = document.getElementById('refresh-btn');

    try {
        isLoading = true;
        refreshBtn.disabled = true;
        statusContainer.innerHTML = '<p class="loading">Loading...</p>';

        const response = await fetch(\`\${API_BASE_URL}/api/data\`);
        
        if (!response.ok) {
            throw new Error('Network response was not ok');
        }

        const data = await response.json();
        
        statusContainer.innerHTML = \`
            <div class="success">
                <p>✅ Connected to API</p>
                <pre>\${JSON.stringify(data, null, 2)}</pre>
            </div>
        \`;
    } catch (error) {
        statusContainer.innerHTML = \`
            <div class="error">
                <p>❌ Error connecting to API: \${error.message}</p>
                <p class="hint">Make sure the backend is running on port ${config.backend === 'fastapi' ? '8000' : '5000'}</p>
            </div>
        \`;
        console.error('Error fetching data:', error);
    } finally {
        isLoading = false;
        refreshBtn.disabled = false;
    }
}

// Initialize on page load
document.addEventListener('DOMContentLoaded', () => {
    fetchData();
    
    const refreshBtn = document.getElementById('refresh-btn');
    refreshBtn.addEventListener('click', fetchData);
});`
    }
  };
}

module.exports = {
  react,
  vue,
  vanilla
};
